### ISSUE TITLE
package doesn't handle JSONRPC headers

### ISSUE THREAD

**Issue by mjKosmic** [ChimeHQ/JSONRPC#13]
It looks like this library doesn't handle JSONRPC headers. There's just a data stream that is fed directly into a `JSONDecoder`. This doesn't work when the full JSONRPC message spec is sent over stdin, like how sourcekit-lsp sends JSONRPC messages to BSP build servers. I haven't verified if the whole message (headers + json payload) are in the data stream sent to the decoder but I think adding a filter to strip out the header characters would be helpful.

**Comment by mjKosmic** [comment]
I was able to verify that the whole message is sent over the data channel.

**Comment by mjKosmic** [comment]
Looks like a filter like this works

```
        Task {
            let filteredStream = AsyncStream<Data> { continuation in
                let stdinStream = FileHandle.standardInput.dataStream
                logger.info("Starting STDIN filter...")
                
                Task { [continuation] in
                    for await data in stdinStream {
                        if let message = String(data: data, encoding: .utf8), let index = message.firstIndex(of: "\r\n") {
                            let json = message.suffix(from: index)
                            if let data = json.data(using: .utf8) {
                                continuation.yield(data)
                            }
                        }
                    }
                }
            }

            let channel = DataChannel.init(writeHandler: DataChannel.stdioPipe().writeHandler, dataSequence: filteredStream)
            let session = JSONRPCSession(channel: channel)
            for await event in await session.eventSequence {
                switch event {
                    case .notification(let notification, let data):
                        logger.info("notification: \(notification.method, privacy: .public)")
                    case .request(let request, let handler, let data): 
                        logger.info("request: \(request.method, privacy: .public)")
                    case .error(let error): 
                        logger.error("error: \(error.localizedDescription, privacy: .public)")
                }
            }
        }
```

NOTE: the logger line was required to kick off the stream. I'm not exactly sure why. Without that log statement the filtered stream never opened

**Comment by mattmassicotte** [comment]
Hello!

Actually, the JSON-RPC spec does not include headers. The format used by the Language Server Protocol is custom. If you are interested in building something from scratch instead, I *think* you should be able to use a `DataChannel.stdioPipe()` for both directions.

I built this library specifically for working with LSP, and I have a [client library](https://github.com/ChimeHQ/LanguageClient) that handles all of these details.

**Comment by mjKosmic** [comment]
Looks like the `DataChannel.withMessageFraming()` offered in your [LanguageServerProtocol](https://github.com/ChimeHQ/LanguageServerProtocol) repo is exactly what i'm looking for! Awesome!

**Comment by mattmassicotte** [comment]
Fantastic! And please let me know if you run into other issues!
